# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ffbbcc74a1780dbf84fe93c254278388c25bcc82c116b5f352732da9f4d502c8f5c8b56badf2a9efdf5d9ad584341d68fa4505e288f0b856e28590db69187ac

test:
  secret_key_base: 99952769e1feb4a4b5608761fd6aba32f511d6e4ed57bcf4e7435d08985293a5a4fedde3a58e5b59dd215d02561644dd30a44c1b77e132fb0393bbba7aa12257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
